language: Java
jdk:
  - openjdk6

branches:
  only:
    - master
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - test-travis

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install protobuf-compiler

script: "mvn clean install "
